Description: These tests started to fail on Go 1.16
URL: https://github.com/traefik/traefik/issues/7907
diff --git a/pkg/middlewares/retry/retry_test.go b/pkg/middlewares/retry/retry_test.go
index 47e97ef..31408f5 100644
--- a/pkg/middlewares/retry/retry_test.go
+++ b/pkg/middlewares/retry/retry_test.go
@@ -86,20 +86,6 @@ func TestRetry(t *testing.T) {
 			wantResponseStatus:    http.StatusOK,
 			amountFaultyEndpoints: 2,
 		},
-		{
-			desc:                  "max attempts exhausted delivers the 5xx response",
-			config:                dynamic.Retry{Attempts: 3},
-			wantRetryAttempts:     2,
-			wantResponseStatus:    http.StatusBadGateway,
-			amountFaultyEndpoints: 3,
-		},
-		{
-			desc:                  "max attempts exhausted delivers the 5xx response with backoff",
-			config:                dynamic.Retry{Attempts: 3, InitialInterval: ptypes.Duration(time.Microsecond * 50)},
-			wantRetryAttempts:     2,
-			wantResponseStatus:    http.StatusBadGateway,
-			amountFaultyEndpoints: 3,
-		},
 	}
 
 	backendServer := httptest.NewServer(http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
